spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: online-store-app
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://localhost:9999
    auth-service:
      path: /user/**
      url: http://localhost:8181/auth/user
security:
  enable-csrf: false
  oauth2:
    resource:
      # to complete the authentication it needs to know where the user info endpoint is in user-service
      userInfoUri: http://localhost:8181/auth/user
    # the filter also needs to know about the client registration with user-service
    client:
      clientId: elasticjee
      clientSecret: elasticjeesecret
      accessTokenUri: http://localhost:8181/auth/oauth/token
      userAuthorizationUri: http://localhost:8181/auth/oauth/authorize
  ignored: /assets/**
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/